apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-sample
  namespace: {{ .Release.Namespace }}
  labels:
    app: rails-sample
    version: {{ .Chart.Version }}
    zorgdomein.nl/logtype: component
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: rails-sample
  template:
    metadata:
      labels:
        app: rails-sample
        version: {{ .Chart.Version }}
        zorgdomein.nl/logtype: component
      annotations:
        fluentbit.io/parser: json
    spec:
      containers:
        - name: rails-sample
          image: "ghcr.io/duartesaraiva98/rails-sample:{{ .Chart.AppVersion }}"
          ports:
          - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /up
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /up
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /up
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          env:
          - name: RAILS_ENV
            value: "production"
          - name: APP_NAME
            value: {{ .Chart.Name }}
{{- with .Values.extraEnv }}
          {{- toYaml . | nindent 10 }}
{{- end }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"